[package]
name = "eventastic_postgres"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
repository = "https://github.com/jdon/eventastic"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
eventastic = { path = "../eventastic" }
sqlx = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
